version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: users-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: harvey
      POSTGRES_PASSWORD: harvey
      POSTGRES_DB: manage-users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
